rotateMatrix: rotate.o rotateMatrix.o
	gcc -o rotateMatrix rotate.o rotateMatrix.o
rotate.o: rotate.c
	gcc -std=gnu99 -pedantic -Wall -Werror -c rotate.c
rotateMatrix.o: rotateMatrix.c
	gcc -std=gnu99 -pedantic -Wall -Werror -c rotateMatrix.c
